// mock-data.ts

export const mockPatients = [
  {
    id: "1",
    name: "John Smith",
    age: "45",
    gender: "Male",
    bloodType: "A+",
    phone: "555-123-4567",
    insuranceProvider: "Blue Cross",
    lastVisit: "2025-02-15",
    fileNumber: "P-10045",
    diagnosis: "Hypertension, Type 2 Diabetes",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    age: "32",
    gender: "Female",
    bloodType: "O-",
    phone: "555-765-4321",
    insuranceProvider: "Aetna",
    lastVisit: "2025-02-28",
    fileNumber: "P-10046",
    diagnosis: "Migraine, Anxiety",
  },
  {
    id: "3",
    name: "Robert Wilson",
    age: "68",
    gender: "Male",
    bloodType: "B+",
    phone: "555-321-9876",
    insuranceProvider: "Medicare",
    lastVisit: "2025-01-20",
    fileNumber: "P-10047",
    diagnosis: "COPD, Coronary Artery Disease",
  },
  {
    id: "4",
    name: "Emily Carter",
    age: "29",
    gender: "Female",
    bloodType: "AB+",
    phone: "555-876-5432",
    insuranceProvider: "United Healthcare",
    lastVisit: "2025-03-01",
    fileNumber: "P-10048",
    diagnosis: "Asthma, Allergic Rhinitis",
  },
  {
    id: "5",
    name: "David Thompson",
    age: "52",
    gender: "Male",
    bloodType: "O+",
    phone: "555-234-5678",
    insuranceProvider: "Blue Cross",
    lastVisit: "2025-02-05",
    fileNumber: "P-10049",
    diagnosis: "Hyperlipidemia, Gout",
  },
  {
    id: "6",
    name: "Lisa Rodriguez",
    age: "41",
    gender: "Female",
    bloodType: "A-",
    phone: "555-345-6789",
    insuranceProvider: "Aetna",
    lastVisit: "2025-02-10",
    fileNumber: "P-10050",
    diagnosis: "Hypothyroidism, Depression",
  },
  {
    id: "7",
    name: "Michael Chen",
    age: "35",
    gender: "Male",
    bloodType: "B-",
    phone: "555-456-7890",
    insuranceProvider: "Medicare",
    lastVisit: "2025-01-15",
    fileNumber: "P-10051",
    diagnosis: "Gastritis, IBS",
  },
  {
    id: "8",
    name: "Jennifer Adams",
    age: "27",
    gender: "Female",
    bloodType: "AB-",
    phone: "555-567-8901",
    insuranceProvider: "United Healthcare",
    lastVisit: "2025-02-22",
    fileNumber: "P-10052",
    diagnosis: "Anemia, Vitamin D Deficiency",
  },
  {
    id: "9",
    name: "Jennifer Adams",
    age: "27",
    gender: "Female",
    bloodType: "AB-",
    phone: "555-567-8901",
    insuranceProvider: "United Healthcare",
    lastVisit: "2025-02-22",
    fileNumber: "P-10052",
    diagnosis: "Anemia, Vitamin D Deficiency",
  },
];
